sonar.organization=muhammadlazaro
sonar.projectKey=SIMPA

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/bootstrap/cache/**,**/*.min.js,**/*.min.css
sonar.php.file.suffixes=php
sonar.javascript.file.suffixes=.js,.vue

sonar.sourceEncoding=UTF-8
